ia_cms:
    menu:
        mainMenu:
            projects:
                name: Projects
                uri: "javascript:;"
                attributes:
                    iconClass: icon_document_alt
                childs:
                    list:
                        name: List Projects
                        route: ia_web_content_thief_projects_index
                    create:
                        name: Create New Project
                        route: ia_web_content_thief_projects_create
                    update:
                        name: Edit Project
                        route: ia_web_content_thief_projects_update
                        routeParameters:
                          id: int
                        display: false
            fieldsets:
                name: Fieldsets
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list:
                        name: List Fieldsets
                        route: ia_web_content_thief_fieldsets_index
                    create:
                        name: Create New Fieldset
                        route: ia_web_content_thief_fieldsets_create
                        display: true
                    update:
                        name: Edit Fieldsets
                        route: ia_web_content_thief_fieldsets_update
                        routeParameters:
                          id: int
                        display: false
                        
            users:
                name: Users
                uri: "javascript:;"
                attributes:
                    iconClass: icon_genius
                childs:
                    list:
                        name: List Users
                        route: ia_users_users_index
                    create:
                        name: Create User
                        route: ia_users_users_create
                        display: true
                    update:
                        name: Edit User
                        route: ia_users_users_update
                        routeParameters:
                          id: int
                        display: false
                        
            
        profileMenu:
            profile:
                name: "My Profile"
                route: ia_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
            logout:
                name: "Log Out"
                route: app_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
            documentation:
                name: "Documentation"
                uri: "javascript:;"
                attributes:
                    iconClass: "fas fa-cog mr-2"
                