payum:
    dynamic_gateways:
        sonata_admin: false
        config_storage: 
            IA\PaymentBundle\Entity\GatewayConfig: { doctrine: orm }

    security:
        token_storage:
            IA\PaymentBundle\Entity\Token: { doctrine: orm }

    storages:
        IA\PaymentBundle\Entity\Agreement: { doctrine: orm }
        IA\PaymentBundle\Entity\Payment: { doctrine: orm }
