payum:              
    storages:
        IA\PaymentBundle\Entity\Agreement: { doctrine: orm }
        IA\PaymentBundle\Entity\Payment: { doctrine: orm }

    security:
        token_storage:
            IA\PaymentBundle\Entity\Token: { doctrine: orm }

    gateways:
        offline_gateway:
            factory: offline
        paypal_express_checkout_gateway:
            factory: paypal_express_checkout
            username: 'sb-ks1wh402232_api1.business.example.com'
            password: '8PRXKLWZFPYBZDKB'
            signature: 'Ajqso8A-uDUaXxl-CdVBwnXhzMsTAEdVwItx7t0TyVJeh7oICslAmTot'
            sandbox: true
        stripe_checkout_gateway:
            factory: stripe_checkout
            publishable_key: 'pk_test_4usJseX4BL8ZuSa9efnggWj800U21erI5Y'
            secret_key:      'sk_test_QHNIIAE1D7L5oqy54cxM4pXD00GO1NH64K'
        paypal_pro_checkout_gateway:
            factory: paypal_pro_checkout
            username: 'sb-5omhg442982_api1.business.example.com'
            password: 'TR5QB2XTSX6WLQU2'
            partner:  'EDIT ME'
            vendor:   'EDIT ME'
            tender:  C
            sandbox: true

ia_payment:
    payment_methods:
        paypal_pro_checkout:
            name: 'Credit Card (PayPal Pro)'
            gateway: paypal_pro_checkout_gateway
            route: ia_payment_paypal_prepare
        paypal_express_checkout:
            name: 'Express Checkout (PayPal)'
            gateway: paypal_express_checkout
            route: ia_payment_paypal_express_checkout_prepare_recurring_payment_agreement
        paypal_express_checkout_recurring_payment:
            name: 'Recurring Checkout (PayPal)'
            gateway: paypal_express_checkout
            route: ia_payment_paypal_express_checkout_prepare_recurring_payment_agreement
        stripe_checkout:
            name: 'Credit Card (STRIPE)'
            gateway: stripe_checkout
            route: ia_payment_stripe_checkout_prepare