payum:              
    storages:
        Payum\Core\Model\Payment: { doctrine: orm }
        IA\PaymentBundle\Entity\AgreementDetails: { doctrine: orm }
        IA\PaymentBundle\Entity\PaymentDetails: { doctrine: orm }

    security:
        token_storage:
            IA\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    gateways:
        offline:
            factory: offline
        paypal_express_checkout_recurring_payment:
            factory: paypal_express_checkout
            #username: 'paypal_test@getnada.com'
            #password: 'Ophth@l@m1@'
            username: 'sb-ks1wh402232_api1.business.example.com'
            password: '8PRXKLWZFPYBZDKB'
            signature: 'Ajqso8A-uDUaXxl-CdVBwnXhzMsTAEdVwItx7t0TyVJeh7oICslAmTot'
            sandbox: true

ia_payment:
    payment_methods:
        paypal_pro_checkout:
            name: 'Credit Card'
            factory: paypal_pro_checkout
            route: ia_payment_paypal_prepare
        paypal_express_checkout_recurring_payment:
            name: 'PayPal'
            factory: paypal_express_checkout
            route: ia_payment_paypal_express_checkout_prepare_recurring_payment_agreement