
# Browser Controller
ia_web_content_thief_browser_browse:
    path:     /browser/browse
    defaults: { _controller: 'App\Controller\BrowserController:browseAction' }

# Fieldsets Controller
ia_web_content_thief_fieldsets:
    resource: |
        alias: ia_web_content_thief.fieldsets
        except: ['show']
        path: /fieldsets
        templates: "pages/Fieldsets"
    type: sylius.resource
    
ia_web_content_thief_fieldsets_index:
    path: /fieldsets
    methods: [GET]
    defaults:
        _controller: ia_web_content_thief.controller.fieldsets:indexAction
        _sylius:
            template: pages/Fieldsets/index.html.twig
            paginate: 3
            sortable: true
            sorting:
                id: desc
#ia_web_content_thief_fieldsets_add_field:
#    path:     /fieldsets/add-field
#    defaults: { _controller: IAWebContentThiefBundle:Fieldsets:addField}
#ia_web_content_thief_fieldsets_list:
#    path:     /fieldsets
#    defaults: { _controller: IAWebContentThiefBundle:Fieldsets:list }
#ia_web_content_thief_fieldsets_edit:
#    path:     /fieldsets/edit/{id}
#    defaults: { _controller: IAWebContentThiefBundle:Fieldsets:edit }
    
ia_web_content_thief_projects:
    resource: |
        alias: ia_web_content_thief.projects
        except: ['show']
        path: /projects
        templates: "pages/Projects"
    type: sylius.resource
    
ia_web_content_projects_add_fields:
    path:     /projects/add-fields
    defaults: { _controller: App\Controller\ProjectsJsonController:addFieldsAction }
    
# Parser Controller
ia_web_content_thief_parser_run_project:
    path:     /parser/run/{projectId}
    defaults: { _controller: 'App\Controller\ParserController:runProjectAction' }
#ia_web_content_thief_parser_run_processor:
#    path:     /parser/run/{processorId}
#    defaults: { _controller: 'IAWebContentThiefBundle:Parser:runProcessor' }
                
# Project Processor Controller
ia_web_content_thief_project_processors_create:
    path:     /processors/create
    defaults: { _controller: App\Controller\ProjectProcessorsController:createAction }

ia_web_content_thief_project_processors_delete:
    path:     /processors/delete/{id}
    defaults: { _controller: App\Controller\ProjectProcessorsController:deleteAction }
    
ia_web_content_thief_project_processors_get_options_form:
    path:     /processors/get-options-form
    defaults: { _controller: App\Controller\ProjectProcessorsController:getOptionsFormAction }
    
ia_web_content_thief_project_processors_get_mappings_form:
    path:     /processors/get-mappings-form
    defaults: { _controller: App\Controller\ProjectProcessorsController:getMappingFormAction }
    
ia_web_content_thief_project_processors_save_mappings:
    path:     /processors/save-mappings/{id}
    defaults: { _controller: App\Controller\ProjectProcessorsController:saveMappingsAction }
