sylius_resource:
    #######################################################################################################################
    # Override default settings
    # -------------------------
    # You Can To Override Many Resource Parameters For All Resources (Including VankoSoft Bundles)
    # View Available Settings in 
    #     \Sylius\Bundle\ResourceBundle\DependencyInjection\Configuration::addSettingsSection(ArrayNodeDefinition $node)
    #######################################################################################################################
    settings:
        paginate: 10
        
    #######################################################################################################################
    # Configure your resources
    #######################################################################################################################
    resources:
        vs_wct.api_hosts:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ApiHost
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\WebContentThief\ApiHostsController
                form:       App\Form\ApiHostForm
        vs_wct.project_categories:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ProjectCategory
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\WebContentThief\ProjectsCategoryController
                form:       App\Form\ProjectCategoryForm
        vs_wct.projects:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Project
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\WebContentThief\ProjectsController
                form:       App\Form\ProjectForm
        vs_wct.project_fields:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ProjectField
                repository: App\Repository\ProjectFieldsRepository
        vs_wct.project_repertories:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ProjectRepertory
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                factory:    Sylius\Component\Resource\Factory\Factory
        vs_wct.project_repertory_items:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ProjectRepertoryItem
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                factory:    Sylius\Component\Resource\Factory\Factory
        vs_wct.project_repertory_fields:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ProjectRepertoryField
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                factory:    Sylius\Component\Resource\Factory\Factory
        vs_wct.project_repertory_fields_files:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ProjectRepertoryFieldFile
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                factory:    Sylius\Component\Resource\Factory\Factory

