twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        applicationIcon: 'build/web-content-thief/images/web-content-thief.svg'
        applicationTitle: '%applicationTitle%'
        applicationEnvironement: '%applicationEnvironemnt%'
        lang: '%lang%'
        locale: '%locale%'
        formCreateAccount: '%vs_users.form_create_account%'
        alerts: '@vs_app.twig.alerts'
        languages: '%languages%'
        installedBundles: '%kernel.bundles%'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    