twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        applicationIcon: 'build/web-content-thief/images/web-content-thief.svg'
        applicationTitle: '%applicationTitle%'
        applicationEnvironement: '%applicationEnvironemnt%'
        formCreateAccount: '%vs_users.form_create_account%'
        installedBundles: '%kernel.bundles%'
        useCkEditor: '%env(resolve:USE_CKEDITOR)%'
        analyticsMeasurementId: '%env(GOOGLE_MEASUREMENT_ID)%'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    