<?php namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParsedItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParsedItemsRepository extends EntityRepository
{

    public function countTotal($projectId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(pi)')
            ->from('App\Entity\ParsedItem', 'pi')
            ->where('pi.projectId = ?1')
            ->setParameters(array(1 => $projectId));
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function lastSession($projectId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('pi.runSession')
            ->from('App\Entity\ParsedItem', 'pi')
            ->where("pi.project = ?1")
            ->orderBy('pi.id', 'DESC')
            ->setMaxResults(1)  // LIMIT
            ->setParameters(array(1 => $projectId));
        $result = $qb->getQuery()->getSingleResult();
        
        return $result['runSession'];
    }
}
