# Browser Controller
#######################
vs_wct_browser_browse:
    path:     /browser/browse
    defaults: { _controller: 'App\Controller\WebContentThief\BrowserController:browseAction' }

vs_wct_browser_test_browser:
    path:     /browser/test-browser
    defaults: { _controller: 'App\Controller\WebContentThief\BrowserController:testBrowserAction' }
    
vs_wct_collector_collect_data:
    path:     /collector/collect-data
    defaults: { _controller: 'App\Controller\WebContentThief\CollectorController:collectDataAction' }

vs_wct_project_preview_repertory:
    path:     /project-repertories/{id}/preview
    defaults: { _controller: 'App\Controller\WebContentThief\ProjectRepertoriesController:previewRepertoryAction' }

vs_wct_project_json_repertory:
    path:     /project-repertories/{id}/get-json
    defaults: { _controller: 'App\Controller\WebContentThief\ProjectRepertoriesController:getJsonAction' }

vs_wct_project_mapper_create:
    path:     /project-mappers/new
    defaults: { _controller: 'App\Controller\WebContentThief\ProjectMappersController:createAction' }

vs_wct_project_mapper_update:
    path:     /project-mappers/{id}/edit
    defaults: { _controller: 'App\Controller\WebContentThief\ProjectMappersController:updateAction' }



