fos_user_security_login:
    path: /login
    controller: App\Controller\AuthController::login
fos_user_security_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    
home:
    path: /
    controller: App\Controller\DefaultController::index

ia_users:
    resource: "@IAUsersBundle/Resources/config/routing/user_management.yml"
    prefix:   /users_bundle/

ia_users_subscription:
    resource: "@IAUsersBundle/Resources/config/routing/subscription.yml"
    prefix:   /users_bundle/subscription/

ia_cms:
    resource: "@IACmsBundle/Resources/config/routing.yml"
    prefix:   /cms
    
ia_payment:
    resource: "@IAPaymentBundle/Resources/config/routing.yml"
    prefix:   /payment
      
test_template_tabs:
    path: /test-template-tabs
    controller: App\Controller\TestTemplateController::tabs
    