fos_user_security_login:
    path: /login
    controller: App\Controller\AuthController::login
fos_user_security_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    
home:
    path: /
    controller: App\Controller\DefaultController::index
 
ia_users:
    resource: "@IAUsersBundle/Resources/config/routing.yml"
    prefix:   /profile/
 
ia_taxonomy:
    resource: "@IATaxonomyBundle/Resources/config/routing.yml"
    prefix: /taxonomy
    
ia_cms:
    resource: "@IACmsBundle/Resources/config/routing.yml"
    prefix:   /cms
    
ia_paid_membership:
    resource: "@IAPaidMembershipBundle/Resources/config/routing.yml"
    prefix:   /membership
    
ia_payment:
    resource: "@IAPaymentBundle/Resources/config/routing.yml"
    prefix:   /payment
      
test_template_tabs:
    path: /test-template-tabs
    controller: App\Controller\TestTemplateController::tabs
    