# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'bg'
    siteTitle: 'VS WebContentThief'
    mailer_user: 'wct@example.com'
    # settings:
        # minuteBonus: 20     # In Percents
        # minutePrice: 0.065

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    app.menu_builder:
        class: App\Component\MenuBuilder
        arguments: ["@security.authorization_checker"]
        calls:
          - [ setContainer ]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: main }
            
    app.profile_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", profileMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: profile }
    
    app.breadcrumbs_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", breadcrumbsMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }
