<?php

namespace IA\WebContentThiefBundle\Entity\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{

    public function countTotal()
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(p) FROM IAWebContentThiefBundle:Project p');

        return $query->getSingleScalarResult();
    }
}
