services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\WebContentThief\:
        resource: '../../../../src/Controller/WebContentThief'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\WebContentThief\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\WebContentThief\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@doctrine'

    App\Controller\WebContentThief\ProjectsController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\WebContentThief\CollectorController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@kernel'
    
    App\Controller\WebContentThief\ServiceSyliusController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_wct.deployers.sylius'
            
    App\Controller\WebContentThief\ProjectMappersController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            
    App\Controller\WebContentThief\ProjectRepertoriesController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '%vs_wct.repertory_fields_files_directory%'
