services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    vs_wct.resources.project_categories.form:
        class: App\Form\ProjectCategoryForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_wct.model.project_categories.class%'
            - '@request_stack'
            
    vs_wct.resources.projects.form:
        class: App\Form\ProjectForm
        tags:
            - { name: form.type }
        arguments:
            - '%vs_wct.model.projects.class%'
            - '@request_stack'
            - '@vs_wct.repository.project_fields'
    
    App\Form\ProjectMapperForm:
        tags:
            - { name: form.type }
        arguments:
            - 'App\Entity\ProjectMapper'
            #- '@vs_wct.repository.project_fields'
            - '@doctrine.orm.entity_manager'
            
    App\Form\Type\MapperFieldType:
        tags:
            - { name: form.type }
        arguments:
            - '@vs_wct.repository.project_fields'
            - '@vs_wct.deployers.sylius'

    