parameters:
    vs_cms.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_cms.gaufrette.app_pictures.filesystem: vs_application_app_pictures
    vs_wct.repertory_fields_files_directory: "%kernel.project_dir%/public/shared_media/gaufrette/repertory_fields_files"
    vs_wct.repertory_fields_files_download_directory: "%kernel.project_dir%/var/system"
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Create a Custom Uploader extending Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
    # Add Needed Configurations in packages/knp_gaufrette.yaml
    ##################################################################################################
    vs_wct.repertory_fields_files_uploader:
        class: App\Component\Uploader\RepertoryFieldFileUploader
        arguments:
            - '@oneup_flysystem.vs_wct_repertory_fields_files_filesystem'
            - '@vs_cms.file_path_generator'
            - '@vs_wct.factory.project_repertory_fields_files'
            - '%vs_wct.repertory_fields_files_download_directory%'


