<?php namespace App\Entity\Repository;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{
    
    public function countTotal()
    {
        $query = $this->getEntityManager()->createQuery( 'SELECT COUNT(p) FROM App\Entity\Project p' );

        return $query->getSingleScalarResult();
    }
}
