app_pricing_plans:
    path: /pricing-plans
    controller: App\Controller\WebContentThiefAPI\PricingPlansController::index

app_pricing_plans_select:
    path: /pricing-plans/select/{pricingPlanId}
    controller: App\Controller\WebContentThiefAPI\PricingPlansController::selectPricingPlan
