vs_application_taxonomy:
    resource: "@VSApplicationBundle/Resources/config/routing/taxonomy.yaml"
    prefix:   /
    options:
        expose: true
 
vs_application_password_generator:
    resource: "@VSApplicationBundle/Resources/config/routing/password_generator.yaml"
    prefix:   /
    options:
        expose: true
        
vs_application_frontend:
    resource: "@VSApplicationBundle/Resources/config/routing/frontend.yaml"
    prefix:   /
    options:
        expose: true

vs_application_about:
    path: /about-application
    controller: App\Controller\WebContentThiefApi\PagesController::aboutApplication

vs_application_contact:
    path: /contact
    controller: App\Controller\WebContentThiefApi\ContactController::index
