# app_vs_catalog_products:
#     resource: "@VSCatalogBundle/Resources/config/routing/products.yaml"
#     prefix: /

# app_vs_catalog_catalog:
#     resource: "@VSCatalogBundle/Resources/config/routing/catalog.yaml"
#     prefix: /

vs_catalog_catalog_latest_products:
    path: /catalog/products/latest
    controller: App\Controller\TestVankosoftApplicationCatalog\CatalogController::latestProductsAction
    
vs_catalog_catalog_category_products:
    path: /catalog/products/{categorySlug}
    controller: App\Controller\TestVankosoftApplicationCatalog\CatalogController::categoryProductsAction
    defaults:
        categorySlug: ''

vs_catalog_catalog_product_show:
    path: /catalog/products/{categorySlug}/{productSlug}
    controller: App\Controller\TestVankosoftApplicationCatalog\CatalogController::showProductAction
    defaults:
        categorySlug: ''
        productSlug: ''

app_vs_catalog_pricing_plans:
    resource: "@VSCatalogBundle/Resources/config/routing/pricing_plans.yaml"
    prefix: /

app_vs_catalog_payment:
    resource: "@VSCatalogBundle/Resources/config/routing/payment.yaml"
    prefix: /

vs_payment_show_payment_methods_form:
    path: /payment-methods
    controller: App\Controller\TestVankosoftApplicationCatalog\ShoppingCartCheckoutController::showPaymentMethodsFormAction
    options:
        expose: true

vs_payment_pricing_plans:
    path: /pricing-plans-checkout
    controller: App\Controller\TestVankosoftApplicationCatalog\PricingPlanCheckoutController::showPricingPlans
    options:
        expose: true
