vs_payment_shopping_cart:
    resource: "@VSPaymentBundle/Resources/config/routing/shopping_cart.yaml"
    prefix: /

vs_payment_checkout:
    resource: "@VSPaymentBundle/Resources/config/routing/checkout.yaml"
    prefix: /

vs_payment_show_credit_card_form:
    path: /credit-card/{formAction}
    controller: App\Controller\WebContentThiefApi\CreditCardController::showCreditCardFormAction
    defaults:
        formAction: ''
    options:
        expose: true
