vs_application:
    menu:
        mainApplicationMenu:
            home:
                name: vs_application.menu.home
                uri: "http://%vankosoft_host%"
                attributes:
                    iconClass: ri-dashboard-2-line
            
            browser:
                name: vs_application.menu.browser
                uri: "javascript:;"
                attributes:
                    iconClass: fas fa-search
                childs:
                    browser_test_browser:
                        name: vs_application.menu.test_browser
                        route: vs_wct_browser_test_browser
            
            projects:
                name: vs_application.menu.projects
                uri: "javascript:;"
                attributes:
                    iconClass: fas fa-project-diagram
                    breadcrumb_route: vs_wct_projects_index
                childs:
                    projects_categories_list:
                        name: vs_application.menu.list_categories
                        route: vs_wct_project_categories_index
                    projects_categories_create:
                        name: vs_application.menu.create_category
                        route: vs_wct_project_categories_create
                    projects_categories_update:
                        name: vs_application.menu.update_category
                        route: vs_wct_project_categories_update
                        routeParameters:
                          id: int
                        display: false
                    projects_list:
                        name: vs_application.menu.list_projects
                        route: vs_wct_projects_index
                    projects_create:
                        name: vs_application.menu.create_project
                        route: vs_wct_projects_create
                    projects_update:
                        name: vs_application.menu.update_project
                        route: vs_wct_projects_update
                        routeParameters:
                          id: int
                        display: false
                    
                    projects_repertory_preview:
                        name: vs_application.menu.project_repertory_preview
                        route: vs_wct_project_preview_repertory
                        routeParameters:
                            id: int
                        display: false
            
            api_hosts:
                name: vs_application.menu.api_hosts
                uri: "javascript:;"
                attributes:
                    iconClass: fas fa-server
                    breadcrumb_route: vs_wct_api_hosts_index
                childs:
                    api_hosts_list:
                        name: vs_application.menu.list_api_hosts
                        route: vs_wct_api_hosts_index
                    api_hosts_create:
                        name: vs_application.menu.create_api_host
                        route: vs_wct_api_hosts_create
                        display: true
                    api_hosts_update:
                        name: vs_application.menu.update_api_host
                        route: vs_wct_api_hosts_update
                        routeParameters:
                          id: int
                        display: false

        profileMenu:
            profile:
                name: vs_application.menu.my_profile
                route: vs_users_profile_show
                attributes:
                    iconClass: "fas fa-user mr-2"
                    target: '_self'
                    
            documentation:
                name: vs_application.menu.documentation
                uri: "http://vankosoft.org/projects/vankosoft-application-project/documentation"
                attributes:
                    iconClass: "fas fa-cog mr-2"
                    target: '_blank'
                    
            language:
                name: vs_application.menu.language
                uri: "javascript:;"
                attributes:
                    id: language
                    iconClass: "fas fa-language mr-2"
                    target: '_self'
                        
            divider_1:
                isDivider: true
            
            logout:
                name: vs_application.menu.logout
                #route: vs_application_logout
                route: app_logout
                attributes:
                    iconClass: "fas fa-power-off mr-2"
                    divider_prepend: false
                    divider_append: true
                    target: '_self'
                    

     